# Generated by Django 2.0.9 on 2019-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('masterdata', '0002_auto_20190717_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization Name', models.CharField(max_length=250, unique=True)),
                ('csr_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Name of Organization head', models.CharField(blank=True, max_length=200, null=True)),
                ('Position of Organization head', models.CharField(blank=True, max_length=200, null=True)),
                ('Email of Organization head', models.EmailField(blank=True, max_length=70, null=True)),
                ('Name of SPOC', models.CharField(blank=True, max_length=200, null=True)),
                ('Position of SPOC', models.CharField(blank=True, max_length=200, null=True)),
                ('Email of SPOC', models.EmailField(blank=True, max_length=70, null=True)),
                ('industry', models.ManyToManyField(blank=True, related_name='org_details', to='masterdata.Industry')),
                ('location_city', models.ManyToManyField(blank=True, related_name='org_city', to='cities_light.City')),
                ('location_state', models.ManyToManyField(blank=True, related_name='org_state', to='cities_light.Region')),
            ],
        ),
    ]
