# Generated by Django 2.0.9 on 2019-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190717_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Email of Organization head',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Email of SPOC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Name of Organization head',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Name of SPOC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Position of Organization head',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Position of SPOC',
        ),
        migrations.AddField(
            model_name='profile',
            name='head_email',
            field=models.EmailField(blank=True, help_text='Email of Organization head', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='head_name',
            field=models.CharField(blank=True, help_text='Name of Organization head', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='head_position',
            field=models.CharField(blank=True, help_text='Position of Organization head', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spoc_email',
            field=models.EmailField(blank=True, help_text='Email of SPOC', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spoc_name',
            field=models.CharField(blank=True, help_text='Name of SPOC', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spoc_position',
            field=models.CharField(blank=True, help_text='Position of SPOC', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Organization Name', max_length=200, unique=True),
        ),
    ]
