# Generated by Django 2.0.9 on 2019-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190717_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Organization name'),
        ),
    ]
