# Generated by Django 2.0.9 on 2019-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_organizationtype_proposalstage_service'),
        ('organization', '0004_auto_20190718_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete='Type of Organization', to='masterdata.OrganizationType'),
        ),
    ]
