# Generated by Django 2.0.9 on 2019-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_engagementtype'),
        ('organization', '0006_auto_20190722_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='engagement_type',
            field=models.ManyToManyField(blank=True, help_text='Type of engagement', to='masterdata.EngagementType'),
        ),
    ]
