# Generated by Django 2.0.9 on 2019-07-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_auto_20190723_0900'),
        ('organization', '0007_profile_engagement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q2', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q3', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('organization', models.ForeignKey(on_delete='Organization', to='organization.Profile')),
                ('qt1', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='scq1', to='masterdata.Question', verbose_name='Q')),
                ('qt2', models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='scq2', to='masterdata.Question', verbose_name='Q')),
                ('qt3', models.OneToOneField(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='scq3', to='masterdata.Question', verbose_name='Q')),
            ],
        ),
    ]
