# Generated by Django 2.0.9 on 2019-07-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_auto_20190723_0900'),
        ('organization', '0008_strategychecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q2', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q3', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('organization', models.ForeignKey(on_delete='Organization', to='organization.Profile')),
                ('qt1', models.OneToOneField(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='scq10', to='masterdata.Question', verbose_name='Q')),
                ('qt2', models.OneToOneField(default=11, on_delete=django.db.models.deletion.PROTECT, related_name='scq11', to='masterdata.Question', verbose_name='Q')),
                ('qt3', models.OneToOneField(default=12, on_delete=django.db.models.deletion.PROTECT, related_name='scq12', to='masterdata.Question', verbose_name='Q')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessPracticeChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q2', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q3', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('organization', models.ForeignKey(on_delete='Organization', to='organization.Profile')),
                ('qt1', models.OneToOneField(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='scq7', to='masterdata.Question', verbose_name='Q')),
                ('qt2', models.OneToOneField(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='scq8', to='masterdata.Question', verbose_name='Q')),
                ('qt3', models.OneToOneField(default=9, on_delete=django.db.models.deletion.PROTECT, related_name='scq9', to='masterdata.Question', verbose_name='Q')),
            ],
        ),
        migrations.CreateModel(
            name='StructureChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q2', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('q3', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A')),
                ('organization', models.ForeignKey(on_delete='Organization', to='organization.Profile')),
                ('qt1', models.OneToOneField(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='scq4', to='masterdata.Question', verbose_name='Q')),
                ('qt2', models.OneToOneField(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='scq5', to='masterdata.Question', verbose_name='Q')),
                ('qt3', models.OneToOneField(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='scq6', to='masterdata.Question', verbose_name='Q')),
            ],
        ),
    ]
