# Generated by Django 2.0.9 on 2019-07-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_partnershiplevel'),
        ('organization', '0009_peoplechecklist_processpracticechecklist_structurechecklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_level', to='masterdata.PartnershipLevel'),
        ),
    ]
