# Generated by Django 2.0.9 on 2019-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('organization', '0010_auto_20190723_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='office_location',
            field=models.ManyToManyField(blank=True, help_text='Select a location', related_name='org_hq', to='cities_light.City', verbose_name='Head Office Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_city',
            field=models.ManyToManyField(blank=True, help_text='Cities with geographical presence', related_name='org_city', to='cities_light.City', verbose_name='CSR Activity - Cities'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_state',
            field=models.ManyToManyField(blank=True, help_text='States with geographical presence', related_name='org_state', to='cities_light.Region', verbose_name='CSR Activity - States'),
        ),
    ]
