# Generated by Django 2.0.9 on 2019-07-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_risklevel'),
        ('organization', '0011_auto_20190725_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='risk_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_level', to='masterdata.RiskLevel'),
        ),
    ]
