# Generated by Django 2.0.9 on 2019-08-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_profile_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplechecklist',
            name='q1',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='peoplechecklist',
            name='q2',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='peoplechecklist',
            name='q3',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='processpracticechecklist',
            name='q1',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='processpracticechecklist',
            name='q2',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='processpracticechecklist',
            name='q3',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='strategychecklist',
            name='q1',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='strategychecklist',
            name='q2',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='strategychecklist',
            name='q3',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='structurechecklist',
            name='q1',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='structurechecklist',
            name='q2',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='structurechecklist',
            name='q3',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='A'),
        ),
    ]
