# Generated by Django 2.0.9 on 2019-08-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20190804_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='partner_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_level', to='masterdata.PartnershipLevel'),
        ),
    ]
