# Generated by Django 2.0.9 on 2019-07-26 08:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0014_risklevel'),
        ('organization', '0012_profile_risk_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget/Value of Proposal')),
                ('imp_partner', models.ManyToManyField(blank=True, help_text='Pick Implementation Partner', related_name='imp_partner', to='organization.Profile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='organization.Profile')),
                ('service', models.ManyToManyField(blank=True, help_text='Service Engaged', to='masterdata.Service')),
                ('spoc', models.ForeignKey(blank=True, help_text='Proposal Handler', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date/Month of Doc/Report')),
                ('doc', models.FileField(blank=True, help_text='Upload file', null=True, unique=True, upload_to='proposal_docs/%Y-%m/')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_proposal', to='KYPSamhita.Proposal')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_stage', to='masterdata.ProposalStage')),
                ('workflow', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_workflow', to='masterdata.Workflow')),
            ],
        ),
    ]
