# Generated by Django 2.0.9 on 2019-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYPSamhita', '0002_proposaldoc_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
