# Generated by Django 2.0.9 on 2019-08-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYPSamhita', '0003_proposal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
