# Generated by Django 2.0.9 on 2019-07-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('organization', '0011_auto_20190725_1031'),
        ('masterdata', '0013_auto_20190723_2202'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('beneficiaries', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of beneficiaries impacted')),
                ('value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget/Value of Program')),
                ('cause_area', models.ManyToManyField(blank=True, help_text='Cause Area', to='masterdata.CauseArea')),
                ('imp_partner', models.ManyToManyField(blank=True, help_text='Pick Implementation Partner', related_name='progimp_partner', to='organization.Profile')),
                ('location_city', models.ManyToManyField(blank=True, help_text='Select State(s) in which program was conducted', related_name='prog_city', to='cities_light.City', verbose_name='Cities')),
                ('location_state', models.ManyToManyField(blank=True, help_text='Select State(s) in which program was conducted', related_name='prog_state', to='cities_light.Region', verbose_name='State(s)')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prog_org', to='organization.Profile')),
            ],
        ),
    ]
