# Generated by Django 2.0.9 on 2019-07-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20190726_0729'),
    ]

    operations = [
    ]
