# Generated by Django 2.0.9 on 2019-07-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20190726_0732'),
    ]

    operations = [
    ]
