# Generated by Django 2.0.9 on 2019-08-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20190726_0843'),
    ]

    operations = [
    ]
