# Generated by Django 2.0.9 on 2019-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20190719_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalstage',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
