# Generated by Django 2.0.9 on 2019-07-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_proposalstage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proposalstage',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='masterdata.Workflow'),
        ),
    ]
