# Generated by Django 2.0.9 on 2019-07-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='name',
            new_name='question',
        ),
    ]
