# Generated by Django 2.0.9 on 2019-07-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20190723_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
