# Generated by Django 2.0.9 on 2019-07-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_partnershiplevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalstage',
            name='dependency',
            field=models.ManyToManyField(blank=True, related_name='_proposalstage_dependency_+', to='masterdata.ProposalStage', verbose_name='Dependencies(if any)'),
        ),
        migrations.AddField(
            model_name='proposalstage',
            name='good_practice',
            field=models.TextField(blank=True, null=True, verbose_name='Good Practices'),
        ),
        migrations.AddField(
            model_name='proposalstage',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='Objectives'),
        ),
        migrations.AddField(
            model_name='proposalstage',
            name='output',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proposalstage',
            name='recurring',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Recurring Output?'),
        ),
    ]
