# Generated by Django 2.0.9 on 2019-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_auto_20190723_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
