# Generated by Django 2.0.9 on 2019-08-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_risklevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstage',
            name='workflow',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='masterdata.Workflow'),
        ),
    ]
